enabled: true
drop_regional: true
global_keywords:
- 全国
- 整体
- 宏观
- 综合
- 主流
- 汇总
- 总结
- 全行业
- 出口
- 进口
- 综合
regional_keywords:
- 北京
- 上海
- 天津
- 重庆
- 河北
- 山西
- 辽宁
- 吉林
- 黑龙江
- 江苏
- 浙江
- 安徽
- 福建
- 江西
- 山东
- 河南
- 湖北
- 湖南
- 广东
- 海南
- 四川
- 贵州
- 云南
- 陕西
- 甘肃
- 青海
- 台湾
- 内蒙古
- 广西
- 西藏
- 宁夏
- 新疆
- 深圳
- 广州
- 乐从
- 佛山
- 唐山
- 邯郸
- 武安
- 安阳
- 沧州
- 邢台
- 承德
- 张家口
- 迁安
- 沈阳
- 大连
- 哈尔滨
- 长春
- 南京
- 无锡
- 徐州
- 杭州
- 宁波
- 温州
- 合肥
- 芜湖
- 福州
- 厦门
- 南昌
- 济南
- 青岛
- 郑州
- 武汉
- 长沙
- 南宁
- 海口
- 成都
- 贵阳
- 昆明
- 西安
- 兰州
- 包头
- 华东
- 华北
- 华南
- 华中
- 西南
- 西北
- 东北
- 江浙
- 沿海
- 沿江
- 曹妃甸
- 京唐港
- 京唐
- 唐山港
- 青岛港
- 日照港
- 连云港
- 天津港
- 上海港
- 黄骅港
exclude_keywords:
- 会议
- 评选
- 通知
- 招聘
- 广告
- 征文
- 活动
- 报名
- 招标
- 中标公示
include_keywords:
- 早报
- 日报
- 周报
- 月报
- 库存
- 产量
- 开工
- 调查
- 快讯
- 调价
- 出厂
- 检修
- 复产
- 停炉
- 焖炉
- 成交
- 需求
- 供给
- 进口
- 出口
- 发运
- 到港
- 疏港
- 价格
- 指数
- 市场
- 分析
- 点评
- 展望
- 钢厂
- 焦化
- 矿山
- 港口
- 铁水
- 高炉
- 电炉
- 螺纹
- 铁矿
- 焦煤
- 焦炭
- 煤焦
